name: CI Pipeline for TypeScript

# Trigger the pipeline on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js and install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Specify your Node.js version

      - name: Install dependencies
        run: |
          npm install

      # Run TypeScript compiler check
      - name: Run TypeScript build
        run: |
          npm run build  # Ensure that the build script exists in your package.json

      # Run unit tests (assuming you use a testing library like Jest)
      - name: Run tests
        run: |
          npm test  # Ensure that you have a test script in package.json

      # Optionally, you can lint the code (if you have eslint set up)
      - name: Lint code
        run: |
          npm run lint  # Make sure to have a lint script in your package.json
